add lesson3
fedor-ches098/rails pull request #4
Opened 2024-03-11 13:44 UTC by fedor-ches098

2024-03-11 19:10 UTC, BubuntuClu requested changes

2024-03-11 19:10 UTC, BubuntuClu commented on TestGuru/db/migrate/20240306174549_create_tests.rb
> +      t.references :user, foreign_key: true
задним числом нельзя править миграции. если нужно внести правки в уже существующе таблицы, то это только через новые миграции

2024-03-11 19:10 UTC, BubuntuClu commented on TestGuru/db/seeds.rb
> +answers = Answer.create!([
а у тебя создались вопросы и ответы? у тебя тут не прописаны привязки к сущностям

2024-03-11 19:11 UTC, BubuntuClu commented on TestGuru/app/models/user.rb
> +    tests.where("level = ?", level)
что возвращает этот запрос?

2024-03-11 19:47 UTC, fedor-ches098 commented on TestGuru/db/migrate/20240306174549_create_tests.rb
> +      t.references :user, foreign_key: true
так как данных никаких изначально не было я решил сделать полный откат бд и затем снова выполнить миграции...но как понимаю так лучше не делать)))

2024-03-12 18:31 UTC, BubuntuClu commented on TestGuru/db/migrate/20240306174549_create_tests.rb
> +      t.references :user, foreign_key: true
да, представляй что ты работаешь с "живой" базой

2024-03-12 18:33 UTC, BubuntuClu commented on TestGuru/app/models/user.rb
> +    tests.joins(:user).where("users.id = ? AND level = ?", self.id, level)
вопрос остается актуальным? что возвращает этот запрос? правда ли он возвращает тесты которые проходил пользователь. чтобы реализовать такое хранение данных надо использовать связь многие-ко-многим, у тебя такое не реализовано

2024-03-14 10:01 UTC, merged